# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-25 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('F', 'Face'), ('B', 'Body'), ('BL', 'Blog')], default='F', max_length=2),
        ),
    ]
