# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-25 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('EC', 'Eczema'), ('PS', 'Psoriasis'), ('AC', 'Acne'), ('RO', 'Rosacea'), ('D', 'Dry Skin'), ('O', 'Oily Skin'), ('S', 'Sensitive'), ('TI', 'Tired Skin'), ('AG', 'Aging Skin'), ('AL', 'Alopecia'), ('PR', 'Pregnancy'), ('CE', 'Cellulite'), ('SC', 'Scarring'), ('SU', 'Sun')], max_length=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', related_query_name='tag', to='products.Product')),
            ],
        ),
    ]
