# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-27 18:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=254)),
                ('body', models.TextField()),
                ('score', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', related_query_name='review', to='products.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', related_query_name='review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='tag',
            name='value',
            field=models.CharField(choices=[('EC', 'Eczema'), ('PS', 'Psoriasis'), ('AC', 'Acne'), ('RO', 'Rosacea'), ('D', 'Dry Skin'), ('O', 'Oily Skin'), ('S', 'Sensitive'), ('TI', 'Tired Skin'), ('AG', 'Aging Skin'), ('AL', 'Alopecia'), ('PR', 'Pregnancy'), ('CE', 'Cellulite'), ('SC', 'Scarring'), ('SU', 'Sun')], max_length=2),
        ),
    ]
