# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-30 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200328_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('C', 'Cleanser'), ('EX', 'Exfoliator'), ('SE', 'Serum'), ('M', 'Moisturiser'), ('SU', 'Sunscreen'), ('T', 'Toner'), ('FM', 'Face Mask'), ('E', 'Eye Cream'), ('CH', 'Chemical')], default='M', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('F', 'Face'), ('B', 'Body')], default='F', max_length=2),
        ),
    ]
